server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:buan4db-order
    username: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 3000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka